name: "Terraform Azure CI/CD"

# Pipeline kab chalegi?
on:
  push:
    branches:
      - main
  workflow_dispatch: # Ek hi baar rahega, isse manual run ka button aa jayega

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform:
    name: "Run Terraform"
    runs-on: ubuntu-latest

    steps:
    # Step 1: Code ko temporary runner par lana
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Azure login (Secrets se credentials uthayega)
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Terraform tool install karna
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    # Step 4: Terraform Init (Bina kisi folder me jaye direct root par)
    - name: Terraform Init
      run: terraform init

    # Step 5: Terraform Plan (Check karega ki kya badlav ho rahe hain)
    - name: Terraform Plan
      run: terraform plan

    # Step 6: Terraform Apply (Yeh Azure par sach me resource bana dega)
    # --auto-approve lagana zaroori hai taaki pipeline yes/no na maange
    - name: Terraform Apply
      run: terraform apply --auto-approve
